INSERT INTO public.cities (id, province_id, name, code) VALUES (1, 1, 'KAB. ACEH SELATAN', '11.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (2, 1, 'KAB. ACEH TENGGARA', '11.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (3, 1, 'KAB. ACEH TIMUR', '11.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (4, 1, 'KAB. ACEH TENGAH', '11.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (5, 1, 'KAB. ACEH BARAT', '11.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (6, 1, 'KAB. ACEH BESAR', '11.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (7, 1, 'KAB. PIDIE', '11.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (8, 1, 'KAB. ACEH UTARA', '11.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (9, 1, 'KAB. SIMEULUE', '11.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (10, 1, 'KAB. ACEH SINGKIL', '11.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (11, 1, 'KAB. BIREUEN', '11.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (12, 1, 'KAB. ACEH BARAT DAYA', '11.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (13, 1, 'KAB. GAYO LUES', '11.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (14, 1, 'KAB. ACEH JAYA', '11.14');
INSERT INTO public.cities (id, province_id, name, code) VALUES (15, 1, 'KAB. NAGAN RAYA', '11.15');
INSERT INTO public.cities (id, province_id, name, code) VALUES (16, 1, 'KAB. ACEH TAMIANG', '11.16');
INSERT INTO public.cities (id, province_id, name, code) VALUES (17, 1, 'KAB. BENER MERIAH', '11.17');
INSERT INTO public.cities (id, province_id, name, code) VALUES (18, 1, 'KAB. PIDIE JAYA', '11.18');
INSERT INTO public.cities (id, province_id, name, code) VALUES (19, 1, 'KOTA BANDA ACEH', '11.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (20, 1, 'KOTA SABANG', '11.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (21, 1, 'KOTA LHOKSEUMAWE', '11.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (22, 1, 'KOTA LANGSA', '11.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (23, 1, 'KOTA SUBULUSSALAM', '11.75');
INSERT INTO public.cities (id, province_id, name, code) VALUES (24, 2, 'KAB. TAPANULI TENGAH', '12.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (25, 2, 'KAB. TAPANULI UTARA', '12.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (26, 2, 'KAB. TAPANULI SELATAN', '12.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (27, 2, 'KAB. NIAS', '12.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (28, 2, 'KAB. LANGKAT', '12.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (29, 2, 'KAB. KARO', '12.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (30, 2, 'KAB. DELI SERDANG', '12.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (31, 2, 'KAB. SIMALUNGUN', '12.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (32, 2, 'KAB. ASAHAN', '12.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (33, 2, 'KAB. LABUHANBATU', '12.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (34, 2, 'KAB. DAIRI', '12.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (35, 2, 'KAB. TOBA SAMOSIR', '12.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (36, 2, 'KAB. MANDAILING NATAL', '12.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (37, 2, 'KAB. NIAS SELATAN', '12.14');
INSERT INTO public.cities (id, province_id, name, code) VALUES (38, 2, 'KAB. PAKPAK BHARAT', '12.15');
INSERT INTO public.cities (id, province_id, name, code) VALUES (39, 2, 'KAB. HUMBANG HASUNDUTAN', '12.16');
INSERT INTO public.cities (id, province_id, name, code) VALUES (40, 2, 'KAB. SAMOSIR', '12.17');
INSERT INTO public.cities (id, province_id, name, code) VALUES (41, 2, 'KAB. SERDANG BEDAGAI', '12.18');
INSERT INTO public.cities (id, province_id, name, code) VALUES (42, 2, 'KAB. BATU BARA', '12.19');
INSERT INTO public.cities (id, province_id, name, code) VALUES (43, 2, 'KAB. PADANG LAWAS UTARA', '12.20');
INSERT INTO public.cities (id, province_id, name, code) VALUES (44, 2, 'KAB. PADANG LAWAS', '12.21');
INSERT INTO public.cities (id, province_id, name, code) VALUES (45, 2, 'KAB. LABUHANBATU SELATAN', '12.22');
INSERT INTO public.cities (id, province_id, name, code) VALUES (46, 2, 'KAB. LABUHANBATU UTARA', '12.23');
INSERT INTO public.cities (id, province_id, name, code) VALUES (47, 2, 'KAB. NIAS UTARA', '12.24');
INSERT INTO public.cities (id, province_id, name, code) VALUES (48, 2, 'KAB. NIAS BARAT', '12.25');
INSERT INTO public.cities (id, province_id, name, code) VALUES (49, 2, 'KOTA MEDAN', '12.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (50, 2, 'KOTA PEMATANGSIANTAR', '12.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (51, 2, 'KOTA SIBOLGA', '12.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (52, 2, 'KOTA TANJUNG BALAI', '12.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (53, 2, 'KOTA BINJAI', '12.75');
INSERT INTO public.cities (id, province_id, name, code) VALUES (54, 2, 'KOTA TEBING TINGGI', '12.76');
INSERT INTO public.cities (id, province_id, name, code) VALUES (55, 2, 'KOTA PADANGSIDIMPUAN', '12.77');
INSERT INTO public.cities (id, province_id, name, code) VALUES (56, 2, 'KOTA GUNUNGSITOLI', '12.78');
INSERT INTO public.cities (id, province_id, name, code) VALUES (57, 3, 'KAB. PESISIR SELATAN', '13.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (58, 3, 'KAB. SOLOK', '13.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (59, 3, 'KAB. SIJUNJUNG', '13.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (60, 3, 'KAB. TANAH DATAR', '13.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (61, 3, 'KAB. PADANG PARIAMAN', '13.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (62, 3, 'KAB. AGAM', '13.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (63, 3, 'KAB. LIMA PULUH KOTA', '13.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (64, 3, 'KAB. PASAMAN', '13.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (65, 3, 'KAB. KEPULAUAN MENTAWAI', '13.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (66, 3, 'KAB. DHARMASRAYA', '13.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (67, 3, 'KAB. SOLOK SELATAN', '13.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (68, 3, 'KAB. PASAMAN BARAT', '13.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (69, 3, 'KOTA PADANG', '13.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (70, 3, 'KOTA SOLOK', '13.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (71, 3, 'KOTA SAWAHLUNTO', '13.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (72, 3, 'KOTA PADANG PANJANG', '13.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (73, 3, 'KOTA BUKITTINGGI', '13.75');
INSERT INTO public.cities (id, province_id, name, code) VALUES (74, 3, 'KOTA PAYAKUMBUH', '13.76');
INSERT INTO public.cities (id, province_id, name, code) VALUES (75, 3, 'KOTA PARIAMAN', '13.77');
INSERT INTO public.cities (id, province_id, name, code) VALUES (76, 4, 'KAB. KAMPAR', '14.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (77, 4, 'KAB. INDRAGIRI HULU', '14.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (78, 4, 'KAB. BENGKALIS', '14.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (79, 4, 'KAB. INDRAGIRI HILIR', '14.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (80, 4, 'KAB. PELALAWAN', '14.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (81, 4, 'KAB. ROKAN HULU', '14.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (82, 4, 'KAB. ROKAN HILIR', '14.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (83, 4, 'KAB. SIAK', '14.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (84, 4, 'KAB. KUANTAN SINGINGI', '14.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (85, 4, 'KAB. KEPULAUAN MERANTI', '14.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (86, 4, 'KOTA PEKANBARU', '14.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (87, 4, 'KOTA DUMAI', '14.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (88, 5, 'KAB. KERINCI', '15.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (89, 5, 'KAB. MERANGIN', '15.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (90, 5, 'KAB. SAROLANGUN', '15.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (91, 5, 'KAB. BATANGHARI', '15.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (92, 5, 'KAB. MUARO JAMBI', '15.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (93, 5, 'KAB. TANJUNG JABUNG BARAT', '15.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (94, 5, 'KAB. TANJUNG JABUNG TIMUR', '15.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (95, 5, 'KAB. BUNGO', '15.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (96, 5, 'KAB. TEBO', '15.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (97, 5, 'KOTA JAMBI', '15.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (98, 5, 'KOTA SUNGAI PENUH', '15.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (99, 6, 'KAB. OGAN KOMERING ULU', '16.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (100, 6, 'KAB. OGAN KOMERING ILIR', '16.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (101, 6, 'KAB. MUARA ENIM', '16.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (102, 6, 'KAB. LAHAT', '16.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (103, 6, 'KAB. MUSI RAWAS', '16.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (104, 6, 'KAB. MUSI BANYUASIN', '16.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (105, 6, 'KAB. BANYUASIN', '16.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (106, 6, 'KAB. OGAN KOMERING ULU TIMUR', '16.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (107, 6, 'KAB. OGAN KOMERING ULU SELATAN', '16.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (108, 6, 'KAB. OGAN ILIR', '16.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (109, 6, 'KAB. EMPAT LAWANG', '16.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (110, 6, 'KAB. PENUKAL ABAB LEMATANG ILIR', '16.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (111, 6, 'KAB. MUSI RAWAS UTARA', '16.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (112, 6, 'KOTA PALEMBANG', '16.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (113, 6, 'KOTA PAGAR ALAM', '16.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (114, 6, 'KOTA LUBUK LINGGAU', '16.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (115, 6, 'KOTA PRABUMULIH', '16.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (233, 15, 'KAB. KEDIRI', '35.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (116, 7, 'KAB. BENGKULU SELATAN', '17.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (117, 7, 'KAB. REJANG LEBONG', '17.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (118, 7, 'KAB. BENGKULU UTARA', '17.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (119, 7, 'KAB. KAUR', '17.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (120, 7, 'KAB. SELUMA', '17.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (121, 7, 'KAB. MUKO MUKO', '17.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (122, 7, 'KAB. LEBONG', '17.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (123, 7, 'KAB. KEPAHIANG', '17.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (124, 7, 'KAB. BENGKULU TENGAH', '17.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (125, 7, 'KOTA BENGKULU', '17.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (126, 8, 'KAB. LAMPUNG SELATAN', '18.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (127, 8, 'KAB. LAMPUNG TENGAH', '18.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (128, 8, 'KAB. LAMPUNG UTARA', '18.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (129, 8, 'KAB. LAMPUNG BARAT', '18.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (130, 8, 'KAB. TULANG BAWANG', '18.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (131, 8, 'KAB. TANGGAMUS', '18.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (132, 8, 'KAB. LAMPUNG TIMUR', '18.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (133, 8, 'KAB. WAY KANAN', '18.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (134, 8, 'KAB. PESAWARAN', '18.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (135, 8, 'KAB. PRINGSEWU', '18.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (136, 8, 'KAB. MESUJI', '18.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (137, 8, 'KAB. TULANG BAWANG BARAT', '18.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (138, 8, 'KAB. PESISIR BARAT', '18.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (139, 8, 'KOTA BANDAR LAMPUNG', '18.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (140, 8, 'KOTA METRO', '18.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (141, 9, 'KAB. BANGKA', '19.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (142, 9, 'KAB. BELITUNG', '19.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (143, 9, 'KAB. BANGKA SELATAN', '19.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (144, 9, 'KAB. BANGKA TENGAH', '19.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (145, 9, 'KAB. BANGKA BARAT', '19.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (146, 9, 'KAB. BELITUNG TIMUR', '19.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (147, 9, 'KOTA PANGKAL PINANG', '19.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (148, 10, 'KAB. BINTAN', '21.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (149, 10, 'KAB. KARIMUN', '21.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (150, 10, 'KAB. NATUNA', '21.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (151, 10, 'KAB. LINGGA', '21.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (152, 10, 'KAB. KEPULAUAN ANAMBAS', '21.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (153, 10, 'KOTA BATAM', '21.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (154, 10, 'KOTA TANJUNG PINANG', '21.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (155, 11, 'KAB. ADM. KEP. SERIBU', '31.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (156, 11, 'KOTA ADM. JAKARTA PUSAT', '31.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (157, 11, 'KOTA ADM. JAKARTA UTARA', '31.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (158, 11, 'KOTA ADM. JAKARTA BARAT', '31.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (159, 11, 'KOTA ADM. JAKARTA SELATAN', '31.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (160, 11, 'KOTA ADM. JAKARTA TIMUR', '31.75');
INSERT INTO public.cities (id, province_id, name, code) VALUES (161, 12, 'KAB. BOGOR', '32.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (162, 12, 'KAB. SUKABUMI', '32.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (163, 12, 'KAB. CIANJUR', '32.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (164, 12, 'KAB. BANDUNG', '32.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (165, 12, 'KAB. GARUT', '32.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (166, 12, 'KAB. TASIKMALAYA', '32.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (167, 12, 'KAB. CIAMIS', '32.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (168, 12, 'KAB. KUNINGAN', '32.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (169, 12, 'KAB. CIREBON', '32.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (170, 12, 'KAB. MAJALENGKA', '32.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (171, 12, 'KAB. SUMEDANG', '32.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (172, 12, 'KAB. INDRAMAYU', '32.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (173, 12, 'KAB. SUBANG', '32.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (174, 12, 'KAB. PURWAKARTA', '32.14');
INSERT INTO public.cities (id, province_id, name, code) VALUES (175, 12, 'KAB. KARAWANG', '32.15');
INSERT INTO public.cities (id, province_id, name, code) VALUES (176, 12, 'KAB. BEKASI', '32.16');
INSERT INTO public.cities (id, province_id, name, code) VALUES (177, 12, 'KAB. BANDUNG BARAT', '32.17');
INSERT INTO public.cities (id, province_id, name, code) VALUES (178, 12, 'KAB. PANGANDARAN', '32.18');
INSERT INTO public.cities (id, province_id, name, code) VALUES (179, 12, 'KOTA BOGOR', '32.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (180, 12, 'KOTA SUKABUMI', '32.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (181, 12, 'KOTA BANDUNG', '32.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (182, 12, 'KOTA CIREBON', '32.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (183, 12, 'KOTA BEKASI', '32.75');
INSERT INTO public.cities (id, province_id, name, code) VALUES (184, 12, 'KOTA DEPOK', '32.76');
INSERT INTO public.cities (id, province_id, name, code) VALUES (185, 12, 'KOTA CIMAHI', '32.77');
INSERT INTO public.cities (id, province_id, name, code) VALUES (186, 12, 'KOTA TASIKMALAYA', '32.78');
INSERT INTO public.cities (id, province_id, name, code) VALUES (187, 12, 'KOTA BANJAR', '32.79');
INSERT INTO public.cities (id, province_id, name, code) VALUES (188, 13, 'KAB. CILACAP', '33.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (189, 13, 'KAB. BANYUMAS', '33.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (190, 13, 'KAB. PURBALINGGA', '33.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (191, 13, 'KAB. BANJARNEGARA', '33.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (192, 13, 'KAB. KEBUMEN', '33.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (193, 13, 'KAB. PURWOREJO', '33.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (194, 13, 'KAB. WONOSOBO', '33.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (195, 13, 'KAB. MAGELANG', '33.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (196, 13, 'KAB. BOYOLALI', '33.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (197, 13, 'KAB. KLATEN', '33.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (198, 13, 'KAB. SUKOHARJO', '33.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (199, 13, 'KAB. WONOGIRI', '33.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (200, 13, 'KAB. KARANGANYAR', '33.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (201, 13, 'KAB. SRAGEN', '33.14');
INSERT INTO public.cities (id, province_id, name, code) VALUES (202, 13, 'KAB. GROBOGAN', '33.15');
INSERT INTO public.cities (id, province_id, name, code) VALUES (203, 13, 'KAB. BLORA', '33.16');
INSERT INTO public.cities (id, province_id, name, code) VALUES (204, 13, 'KAB. REMBANG', '33.17');
INSERT INTO public.cities (id, province_id, name, code) VALUES (205, 13, 'KAB. PATI', '33.18');
INSERT INTO public.cities (id, province_id, name, code) VALUES (206, 13, 'KAB. KUDUS', '33.19');
INSERT INTO public.cities (id, province_id, name, code) VALUES (207, 13, 'KAB. JEPARA', '33.20');
INSERT INTO public.cities (id, province_id, name, code) VALUES (208, 13, 'KAB. DEMAK', '33.21');
INSERT INTO public.cities (id, province_id, name, code) VALUES (209, 13, 'KAB. SEMARANG', '33.22');
INSERT INTO public.cities (id, province_id, name, code) VALUES (210, 13, 'KAB. TEMANGGUNG', '33.23');
INSERT INTO public.cities (id, province_id, name, code) VALUES (211, 13, 'KAB. KENDAL', '33.24');
INSERT INTO public.cities (id, province_id, name, code) VALUES (212, 13, 'KAB. BATANG', '33.25');
INSERT INTO public.cities (id, province_id, name, code) VALUES (213, 13, 'KAB. PEKALONGAN', '33.26');
INSERT INTO public.cities (id, province_id, name, code) VALUES (214, 13, 'KAB. PEMALANG', '33.27');
INSERT INTO public.cities (id, province_id, name, code) VALUES (215, 13, 'KAB. TEGAL', '33.28');
INSERT INTO public.cities (id, province_id, name, code) VALUES (216, 13, 'KAB. BREBES', '33.29');
INSERT INTO public.cities (id, province_id, name, code) VALUES (217, 13, 'KOTA MAGELANG', '33.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (218, 13, 'KOTA SURAKARTA', '33.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (219, 13, 'KOTA SALATIGA', '33.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (220, 13, 'KOTA SEMARANG', '33.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (221, 13, 'KOTA PEKALONGAN', '33.75');
INSERT INTO public.cities (id, province_id, name, code) VALUES (222, 13, 'KOTA TEGAL', '33.76');
INSERT INTO public.cities (id, province_id, name, code) VALUES (223, 14, 'KAB. KULON PROGO', '34.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (224, 14, 'KAB. BANTUL', '34.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (225, 14, 'KAB. GUNUNGKIDUL', '34.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (226, 14, 'KAB. SLEMAN', '34.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (227, 14, 'KOTA YOGYAKARTA', '34.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (228, 15, 'KAB. PACITAN', '35.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (229, 15, 'KAB. PONOROGO', '35.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (230, 15, 'KAB. TRENGGALEK', '35.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (231, 15, 'KAB. TULUNGAGUNG', '35.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (232, 15, 'KAB. BLITAR', '35.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (234, 15, 'KAB. MALANG', '35.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (235, 15, 'KAB. LUMAJANG', '35.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (236, 15, 'KAB. JEMBER', '35.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (237, 15, 'KAB. BANYUWANGI', '35.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (238, 15, 'KAB. BONDOWOSO', '35.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (239, 15, 'KAB. SITUBONDO', '35.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (240, 15, 'KAB. PROBOLINGGO', '35.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (241, 15, 'KAB. PASURUAN', '35.14');
INSERT INTO public.cities (id, province_id, name, code) VALUES (242, 15, 'KAB. SIDOARJO', '35.15');
INSERT INTO public.cities (id, province_id, name, code) VALUES (243, 15, 'KAB. MOJOKERTO', '35.16');
INSERT INTO public.cities (id, province_id, name, code) VALUES (244, 15, 'KAB. JOMBANG', '35.17');
INSERT INTO public.cities (id, province_id, name, code) VALUES (245, 15, 'KAB. NGANJUK', '35.18');
INSERT INTO public.cities (id, province_id, name, code) VALUES (246, 15, 'KAB. MADIUN', '35.19');
INSERT INTO public.cities (id, province_id, name, code) VALUES (247, 15, 'KAB. MAGETAN', '35.20');
INSERT INTO public.cities (id, province_id, name, code) VALUES (248, 15, 'KAB. NGAWI', '35.21');
INSERT INTO public.cities (id, province_id, name, code) VALUES (249, 15, 'KAB. BOJONEGORO', '35.22');
INSERT INTO public.cities (id, province_id, name, code) VALUES (250, 15, 'KAB. TUBAN', '35.23');
INSERT INTO public.cities (id, province_id, name, code) VALUES (251, 15, 'KAB. LAMONGAN', '35.24');
INSERT INTO public.cities (id, province_id, name, code) VALUES (252, 15, 'KAB. GRESIK', '35.25');
INSERT INTO public.cities (id, province_id, name, code) VALUES (253, 15, 'KAB. BANGKALAN', '35.26');
INSERT INTO public.cities (id, province_id, name, code) VALUES (254, 15, 'KAB. SAMPANG', '35.27');
INSERT INTO public.cities (id, province_id, name, code) VALUES (255, 15, 'KAB. PAMEKASAN', '35.28');
INSERT INTO public.cities (id, province_id, name, code) VALUES (256, 15, 'KAB. SUMENEP', '35.29');
INSERT INTO public.cities (id, province_id, name, code) VALUES (257, 15, 'KOTA KEDIRI', '35.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (258, 15, 'KOTA BLITAR', '35.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (259, 15, 'KOTA MALANG', '35.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (260, 15, 'KOTA PROBOLINGGO', '35.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (261, 15, 'KOTA PASURUAN', '35.75');
INSERT INTO public.cities (id, province_id, name, code) VALUES (262, 15, 'KOTA MOJOKERTO', '35.76');
INSERT INTO public.cities (id, province_id, name, code) VALUES (263, 15, 'KOTA MADIUN', '35.77');
INSERT INTO public.cities (id, province_id, name, code) VALUES (264, 15, 'KOTA SURABAYA', '35.78');
INSERT INTO public.cities (id, province_id, name, code) VALUES (265, 15, 'KOTA BATU', '35.79');
INSERT INTO public.cities (id, province_id, name, code) VALUES (266, 16, 'KAB. PANDEGLANG', '36.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (267, 16, 'KAB. LEBAK', '36.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (268, 16, 'KAB. TANGERANG', '36.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (269, 16, 'KAB. SERANG', '36.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (270, 16, 'KOTA TANGERANG', '36.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (271, 16, 'KOTA CILEGON', '36.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (272, 16, 'KOTA SERANG', '36.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (273, 16, 'KOTA TANGERANG SELATAN', '36.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (274, 17, 'KAB. JEMBRANA', '51.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (275, 17, 'KAB. TABANAN', '51.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (276, 17, 'KAB. BADUNG', '51.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (277, 17, 'KAB. GIANYAR', '51.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (278, 17, 'KAB. KLUNGKUNG', '51.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (279, 17, 'KAB. BANGLI', '51.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (280, 17, 'KAB. KARANGASEM', '51.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (281, 17, 'KAB. BULELENG', '51.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (282, 17, 'KOTA DENPASAR', '51.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (283, 18, 'KAB. LOMBOK BARAT', '52.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (284, 18, 'KAB. LOMBOK TENGAH', '52.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (285, 18, 'KAB. LOMBOK TIMUR', '52.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (286, 18, 'KAB. SUMBAWA', '52.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (287, 18, 'KAB. DOMPU', '52.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (288, 18, 'KAB. BIMA', '52.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (289, 18, 'KAB. SUMBAWA BARAT', '52.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (290, 18, 'KAB. LOMBOK UTARA', '52.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (291, 18, 'KOTA MATARAM', '52.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (292, 18, 'KOTA BIMA', '52.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (293, 19, 'KAB. KUPANG', '53.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (294, 19, 'KAB TIMOR TENGAH SELATAN', '53.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (295, 19, 'KAB. TIMOR TENGAH UTARA', '53.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (296, 19, 'KAB. BELU', '53.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (297, 19, 'KAB. ALOR', '53.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (298, 19, 'KAB. FLORES TIMUR', '53.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (299, 19, 'KAB. SIKKA', '53.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (300, 19, 'KAB. ENDE', '53.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (301, 19, 'KAB. NGADA', '53.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (302, 19, 'KAB. MANGGARAI', '53.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (303, 19, 'KAB. SUMBA TIMUR', '53.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (304, 19, 'KAB. SUMBA BARAT', '53.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (305, 19, 'KAB. LEMBATA', '53.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (306, 19, 'KAB. ROTE NDAO', '53.14');
INSERT INTO public.cities (id, province_id, name, code) VALUES (307, 19, 'KAB. MANGGARAI BARAT', '53.15');
INSERT INTO public.cities (id, province_id, name, code) VALUES (308, 19, 'KAB. NAGEKEO', '53.16');
INSERT INTO public.cities (id, province_id, name, code) VALUES (309, 19, 'KAB. SUMBA TENGAH', '53.17');
INSERT INTO public.cities (id, province_id, name, code) VALUES (310, 19, 'KAB. SUMBA BARAT DAYA', '53.18');
INSERT INTO public.cities (id, province_id, name, code) VALUES (311, 19, 'KAB. MANGGARAI TIMUR', '53.19');
INSERT INTO public.cities (id, province_id, name, code) VALUES (312, 19, 'KAB. SABU RAIJUA', '53.20');
INSERT INTO public.cities (id, province_id, name, code) VALUES (313, 19, 'KAB. MALAKA', '53.21');
INSERT INTO public.cities (id, province_id, name, code) VALUES (314, 19, 'KOTA KUPANG', '53.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (315, 20, 'KAB. SAMBAS', '61.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (316, 20, 'KAB. MEMPAWAH', '61.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (317, 20, 'KAB. SANGGAU', '61.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (318, 20, 'KAB. KETAPANG', '61.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (319, 20, 'KAB. SINTANG', '61.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (320, 20, 'KAB. KAPUAS HULU', '61.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (321, 20, 'KAB. BENGKAYANG', '61.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (322, 20, 'KAB. LANDAK', '61.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (323, 20, 'KAB. SEKADAU', '61.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (324, 20, 'KAB. MELAWI', '61.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (325, 20, 'KAB. KAYONG UTARA', '61.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (326, 20, 'KAB. KUBU RAYA', '61.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (327, 20, 'KOTA PONTIANAK', '61.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (328, 20, 'KOTA SINGKAWANG', '61.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (329, 21, 'KAB. KOTAWARINGIN BARAT', '62.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (330, 21, 'KAB. KOTAWARINGIN TIMUR', '62.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (331, 21, 'KAB. KAPUAS', '62.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (332, 21, 'KAB. BARITO SELATAN', '62.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (333, 21, 'KAB. BARITO UTARA', '62.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (334, 21, 'KAB. KATINGAN', '62.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (335, 21, 'KAB. SERUYAN', '62.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (336, 21, 'KAB. SUKAMARA', '62.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (337, 21, 'KAB. LAMANDAU', '62.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (338, 21, 'KAB. GUNUNG MAS', '62.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (339, 21, 'KAB. PULANG PISAU', '62.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (340, 21, 'KAB. MURUNG RAYA', '62.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (341, 21, 'KAB. BARITO TIMUR', '62.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (342, 21, 'KOTA PALANGKARAYA', '62.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (343, 22, 'KAB. TANAH LAUT', '63.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (344, 22, 'KAB. KOTABARU', '63.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (345, 22, 'KAB. BANJAR', '63.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (346, 22, 'KAB. BARITO KUALA', '63.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (347, 22, 'KAB. TAPIN', '63.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (348, 22, 'KAB. HULU SUNGAI SELATAN', '63.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (349, 22, 'KAB. HULU SUNGAI TENGAH', '63.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (350, 22, 'KAB. HULU SUNGAI UTARA', '63.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (351, 22, 'KAB. TABALONG', '63.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (352, 22, 'KAB. TANAH BUMBU', '63.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (353, 22, 'KAB. BALANGAN', '63.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (354, 22, 'KOTA BANJARMASIN', '63.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (355, 22, 'KOTA BANJARBARU', '63.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (356, 23, 'KAB. PASER', '64.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (357, 23, 'KAB. KUTAI KARTANEGARA', '64.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (358, 23, 'KAB. BERAU', '64.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (359, 23, 'KAB. KUTAI BARAT', '64.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (360, 23, 'KAB. KUTAI TIMUR', '64.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (361, 23, 'KAB. PENAJAM PASER UTARA', '64.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (362, 23, 'KAB. MAHAKAM ULU', '64.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (363, 23, 'KOTA BALIKPAPAN', '64.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (364, 23, 'KOTA SAMARINDA', '64.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (365, 23, 'KOTA BONTANG', '64.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (366, 24, 'KAB. BULUNGAN', '65.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (367, 24, 'KAB. MALINAU', '65.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (368, 24, 'KAB. NUNUKAN', '65.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (369, 24, 'KAB. TANA TIDUNG', '65.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (370, 24, 'KOTA TARAKAN', '65.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (371, 25, 'KAB. BOLAANG MONGONDOW', '71.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (372, 25, 'KAB. MINAHASA', '71.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (373, 25, 'KAB. KEPULAUAN SANGIHE', '71.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (374, 25, 'KAB. KEPULAUAN TALAUD', '71.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (375, 25, 'KAB. MINAHASA SELATAN', '71.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (376, 25, 'KAB. MINAHASA UTARA', '71.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (377, 25, 'KAB. MINAHASA TENGGARA', '71.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (378, 25, 'KAB. BOLAANG MONGONDOW UTARA', '71.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (379, 25, 'KAB. KEP. SIAU TAGULANDANG BIARO', '71.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (380, 25, 'KAB. BOLAANG MONGONDOW TIMUR', '71.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (381, 25, 'KAB. BOLAANG MONGONDOW SELATAN', '71.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (382, 25, 'KOTA MANADO', '71.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (383, 25, 'KOTA BITUNG', '71.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (384, 25, 'KOTA TOMOHON', '71.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (385, 25, 'KOTA KOTAMOBAGU', '71.74');
INSERT INTO public.cities (id, province_id, name, code) VALUES (386, 26, 'KAB. BANGGAI', '72.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (387, 26, 'KAB. POSO', '72.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (388, 26, 'KAB. DONGGALA', '72.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (389, 26, 'KAB. TOLI TOLI', '72.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (390, 26, 'KAB. BUOL', '72.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (391, 26, 'KAB. MOROWALI', '72.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (392, 26, 'KAB. BANGGAI KEPULAUAN', '72.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (393, 26, 'KAB. PARIGI MOUTONG', '72.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (394, 26, 'KAB. TOJO UNA UNA', '72.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (395, 26, 'KAB. SIGI', '72.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (396, 26, 'KAB. BANGGAI LAUT', '72.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (397, 26, 'KAB. MOROWALI UTARA', '72.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (398, 26, 'KOTA PALU', '72.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (399, 27, 'KAB. KEPULAUAN SELAYAR', '73.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (400, 27, 'KAB. BULUKUMBA', '73.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (401, 27, 'KAB. BANTAENG', '73.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (402, 27, 'KAB. JENEPONTO', '73.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (403, 27, 'KAB. TAKALAR', '73.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (404, 27, 'KAB. GOWA', '73.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (405, 27, 'KAB. SINJAI', '73.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (406, 27, 'KAB. BONE', '73.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (407, 27, 'KAB. MAROS', '73.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (408, 27, 'KAB. PANGKAJENE KEPULAUAN', '73.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (409, 27, 'KAB. BARRU', '73.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (410, 27, 'KAB. SOPPENG', '73.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (411, 27, 'KAB. WAJO', '73.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (412, 27, 'KAB. SIDENRENG RAPPANG', '73.14');
INSERT INTO public.cities (id, province_id, name, code) VALUES (413, 27, 'KAB. PINRANG', '73.15');
INSERT INTO public.cities (id, province_id, name, code) VALUES (414, 27, 'KAB. ENREKANG', '73.16');
INSERT INTO public.cities (id, province_id, name, code) VALUES (415, 27, 'KAB. LUWU', '73.17');
INSERT INTO public.cities (id, province_id, name, code) VALUES (416, 27, 'KAB. TANA TORAJA', '73.18');
INSERT INTO public.cities (id, province_id, name, code) VALUES (417, 27, 'KAB. LUWU UTARA', '73.22');
INSERT INTO public.cities (id, province_id, name, code) VALUES (418, 27, 'KAB. LUWU TIMUR', '73.24');
INSERT INTO public.cities (id, province_id, name, code) VALUES (419, 27, 'KAB. TORAJA UTARA', '73.26');
INSERT INTO public.cities (id, province_id, name, code) VALUES (420, 27, 'KOTA MAKASSAR', '73.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (421, 27, 'KOTA PARE PARE', '73.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (422, 27, 'KOTA PALOPO', '73.73');
INSERT INTO public.cities (id, province_id, name, code) VALUES (423, 28, 'KAB. KOLAKA', '74.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (424, 28, 'KAB. KONAWE', '74.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (425, 28, 'KAB. MUNA', '74.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (426, 28, 'KAB. BUTON', '74.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (427, 28, 'KAB. KONAWE SELATAN', '74.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (428, 28, 'KAB. BOMBANA', '74.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (429, 28, 'KAB. WAKATOBI', '74.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (430, 28, 'KAB. KOLAKA UTARA', '74.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (431, 28, 'KAB. KONAWE UTARA', '74.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (432, 28, 'KAB. BUTON UTARA', '74.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (433, 28, 'KAB. KOLAKA TIMUR', '74.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (434, 28, 'KAB. KONAWE KEPULAUAN', '74.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (435, 28, 'KAB. MUNA BARAT', '74.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (436, 28, 'KAB. BUTON TENGAH', '74.14');
INSERT INTO public.cities (id, province_id, name, code) VALUES (437, 28, 'KAB. BUTON SELATAN', '74.15');
INSERT INTO public.cities (id, province_id, name, code) VALUES (438, 28, 'KOTA KENDARI', '74.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (439, 28, 'KOTA BAU BAU', '74.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (440, 29, 'KAB. GORONTALO', '75.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (441, 29, 'KAB. BOALEMO', '75.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (442, 29, 'KAB. BONE BOLANGO', '75.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (443, 29, 'KAB. PAHUWATO', '75.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (444, 29, 'KAB. GORONTALO UTARA', '75.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (445, 29, 'KOTA GORONTALO', '75.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (446, 30, 'KAB. MAMUJU UTARA', '76.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (447, 30, 'KAB. MAMUJU', '76.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (448, 30, 'KAB. MAMASA', '76.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (449, 30, 'KAB. POLEWALI MANDAR', '76.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (450, 30, 'KAB. MAJENE', '76.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (451, 30, 'KAB. MAMUJU TENGAH', '76.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (452, 31, 'KAB. MALUKU TENGAH', '81.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (453, 31, 'KAB. MALUKU TENGGARA', '81.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (454, 31, 'KAB. MALUKU TENGGARA BARAT', '81.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (455, 31, 'KAB. BURU', '81.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (456, 31, 'KAB. SERAM BAGIAN TIMUR', '81.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (457, 31, 'KAB. SERAM BAGIAN BARAT', '81.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (458, 31, 'KAB. KEPULAUAN ARU', '81.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (459, 31, 'KAB. MALUKU BARAT DAYA', '81.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (460, 31, 'KAB. BURU SELATAN', '81.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (461, 31, 'KOTA AMBON', '81.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (462, 31, 'KOTA TUAL', '81.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (463, 32, 'KAB. HALMAHERA BARAT', '82.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (464, 32, 'KAB. HALMAHERA TENGAH', '82.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (465, 32, 'KAB. HALMAHERA UTARA', '82.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (466, 32, 'KAB. HALMAHERA SELATAN', '82.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (467, 32, 'KAB. KEPULAUAN SULA', '82.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (468, 32, 'KAB. HALMAHERA TIMUR', '82.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (469, 32, 'KAB. PULAU MOROTAI', '82.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (470, 32, 'KAB. PULAU TALIABU', '82.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (471, 32, 'KOTA TERNATE', '82.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (472, 32, 'KOTA TIDORE KEPULAUAN', '82.72');
INSERT INTO public.cities (id, province_id, name, code) VALUES (473, 33, 'KAB. MERAUKE', '91.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (474, 33, 'KAB. JAYAWIJAYA', '91.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (475, 33, 'KAB. JAYAPURA', '91.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (476, 33, 'KAB. NABIRE', '91.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (477, 33, 'KAB. KEPULAUAN YAPEN', '91.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (478, 33, 'KAB. BIAK NUMFOR', '91.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (479, 33, 'KAB. PUNCAK JAYA', '91.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (480, 33, 'KAB. PANIAI', '91.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (481, 33, 'KAB. MIMIKA', '91.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (482, 33, 'KAB. SARMI', '91.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (483, 33, 'KAB. KEEROM', '91.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (484, 33, 'KAB. PEGUNUNGAN BINTANG', '91.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (485, 33, 'KAB. YAHUKIMO', '91.13');
INSERT INTO public.cities (id, province_id, name, code) VALUES (486, 33, 'KAB. TOLIKARA', '91.14');
INSERT INTO public.cities (id, province_id, name, code) VALUES (487, 33, 'KAB. WAROPEN', '91.15');
INSERT INTO public.cities (id, province_id, name, code) VALUES (488, 33, 'KAB. BOVEN DIGOEL', '91.16');
INSERT INTO public.cities (id, province_id, name, code) VALUES (489, 33, 'KAB. MAPPI', '91.17');
INSERT INTO public.cities (id, province_id, name, code) VALUES (490, 33, 'KAB. ASMAT', '91.18');
INSERT INTO public.cities (id, province_id, name, code) VALUES (491, 33, 'KAB. SUPIORI', '91.19');
INSERT INTO public.cities (id, province_id, name, code) VALUES (492, 33, 'KAB. MAMBERAMO RAYA', '91.20');
INSERT INTO public.cities (id, province_id, name, code) VALUES (493, 33, 'KAB. MAMBERAMO TENGAH', '91.21');
INSERT INTO public.cities (id, province_id, name, code) VALUES (494, 33, 'KAB. YALIMO', '91.22');
INSERT INTO public.cities (id, province_id, name, code) VALUES (495, 33, 'KAB. LANNY JAYA', '91.23');
INSERT INTO public.cities (id, province_id, name, code) VALUES (496, 33, 'KAB. NDUGA', '91.24');
INSERT INTO public.cities (id, province_id, name, code) VALUES (497, 33, 'KAB. PUNCAK', '91.25');
INSERT INTO public.cities (id, province_id, name, code) VALUES (498, 33, 'KAB. DOGIYAI', '91.26');
INSERT INTO public.cities (id, province_id, name, code) VALUES (499, 33, 'KAB. INTAN JAYA', '91.27');
INSERT INTO public.cities (id, province_id, name, code) VALUES (500, 33, 'KAB. DEIYAI', '91.28');
INSERT INTO public.cities (id, province_id, name, code) VALUES (501, 33, 'KOTA JAYAPURA', '91.71');
INSERT INTO public.cities (id, province_id, name, code) VALUES (502, 34, 'KAB. SORONG', '92.01');
INSERT INTO public.cities (id, province_id, name, code) VALUES (503, 34, 'KAB. MANOKWARI', '92.02');
INSERT INTO public.cities (id, province_id, name, code) VALUES (504, 34, 'KAB. FAK FAK', '92.03');
INSERT INTO public.cities (id, province_id, name, code) VALUES (505, 34, 'KAB. SORONG SELATAN', '92.04');
INSERT INTO public.cities (id, province_id, name, code) VALUES (506, 34, 'KAB. RAJA AMPAT', '92.05');
INSERT INTO public.cities (id, province_id, name, code) VALUES (507, 34, 'KAB. TELUK BINTUNI', '92.06');
INSERT INTO public.cities (id, province_id, name, code) VALUES (508, 34, 'KAB. TELUK WONDAMA', '92.07');
INSERT INTO public.cities (id, province_id, name, code) VALUES (509, 34, 'KAB. KAIMANA', '92.08');
INSERT INTO public.cities (id, province_id, name, code) VALUES (510, 34, 'KAB. TAMBRAUW', '92.09');
INSERT INTO public.cities (id, province_id, name, code) VALUES (511, 34, 'KAB. MAYBRAT', '92.10');
INSERT INTO public.cities (id, province_id, name, code) VALUES (512, 34, 'KAB. MANOKWARI SELATAN', '92.11');
INSERT INTO public.cities (id, province_id, name, code) VALUES (513, 34, 'KAB. PEGUNUNGAN ARFAK', '92.12');
INSERT INTO public.cities (id, province_id, name, code) VALUES (514, 34, 'KOTA SORONG', '92.71');