INSERT INTO public.provinces (id, country_id, name, code) VALUES (1, 1, 'ACEH', '11');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (2, 1, 'SUMATERA UTARA', '12');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (3, 1, 'SUMATERA BARAT', '13');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (4, 1, 'RIAU', '14');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (5, 1, 'JAMBI', '15');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (6, 1, 'SUMATERA SELATAN', '16');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (7, 1, 'BENGKULU', '17');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (8, 1, 'LAMPUNG', '18');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (9, 1, 'KEPULAUAN BANGKA BELITUNG', '19');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (10, 1, 'KEPULAUAN RIAU', '21');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (11, 1, 'DKI JAKARTA', '31');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (12, 1, 'JAWA BARAT', '32');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (13, 1, 'JAWA TENGAH', '33');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (14, 1, 'DAERAH ISTIMEWA YOGYAKARTA', '34');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (15, 1, 'JAWA TIMUR', '35');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (16, 1, 'BANTEN', '36');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (17, 1, 'BALI', '51');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (18, 1, 'NUSA TENGGARA BARAT', '52');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (19, 1, 'NUSA TENGGARA TIMUR', '53');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (20, 1, 'KALIMANTAN BARAT', '61');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (21, 1, 'KALIMANTAN TENGAH', '62');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (22, 1, 'KALIMANTAN SELATAN', '63');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (23, 1, 'KALIMANTAN TIMUR', '64');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (24, 1, 'KALIMANTAN UTARA', '65');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (25, 1, 'SULAWESI UTARA', '71');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (26, 1, 'SULAWESI TENGAH', '72');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (27, 1, 'SULAWESI SELATAN', '73');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (28, 1, 'SULAWESI TENGGARA', '74');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (29, 1, 'GORONTALO', '75');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (30, 1, 'SULAWESI BARAT', '76');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (31, 1, 'MALUKU', '81');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (32, 1, 'MALUKU UTARA', '82');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (33, 1, 'PAPUA', '91');
INSERT INTO public.provinces (id, country_id, name, code) VALUES (34, 1, 'PAPUA BARAT', '92');